version: '3'

services:
  mariadb:
    image: mariadb
    container_name: demoDB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=demo
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3366:3306
    volumes:
      - ./docker/maria/sql:/var/lib/mysql
    restart: always
    networks:
      - demo
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    depends_on:
      - mariadb
    ports:
      - 7979:7070
    networks:
      - demo

networks:
  demo:
    driver: bridge
